name: CI

on:
  push:
    branches: [ main, develop, initial ]
  pull_request:
    branches: [ main, develop, initial ]

jobs:
  build:

    runs-on: ubuntu-latest
    strategy:
      fail-fast: true
      matrix:
        python-version: ["3.7", "3.8", "3.9"]
    name: Python ${{ matrix.python-version }}

    steps:
    - name: Checkout repo
      uses: actions/checkout@v2

    - name: Set up Python versions
      uses: actions/setup-python@v2
      with:
        python-version: ${{ matrix.python-version }}

    - name: Install nox
      run: pip install nox==2020.12.31

    - name: Install poetry
      run: pip install poetry==1.1.4

    - name: Run nox
      run: nox
